theme: jekyll-theme-slate
author: David Garcia, Stefan Thalmann, Eduardo Veas, Elisabeth Lex, Viktoria Pammer-Schindler, Markus Hadler, Guilherme Maia de Oliveira Wood, Matthias Wendland
title: Introduction to Computational Social Systems
